name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey ! Welcome aboard! 🚀 Ready to dive into the WEB universe with us? /n Get set for a tech-tastic journey filled with laughs, coffee, and the occasional CTRL+ALT+DEL moment. /n Need a hand with anything? Just give a shout. Let's rock this WEB world together! /n Cheers, Fraser."
        pr-message: " Letts Pull this code , Thanks Fraser."
